image: docker:19.03.12

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.12-dind

before_script:
  - docker info

build-frontend:
  stage: build
  script:
    - docker build -t janvesely92/dt-frontend ./frontend
    - docker login
    - docker push janvesely92/dt-frontend


build-backend:
  stage: build
  script:
    - docker build -t janvesely92/dt-backend ./backend
    - docker login
    - docker push janvesely92/dt-backend
