version: "3.9"  # optional since v1.27.0
services:
  ktor:
    image: janvesely92/dt-backend
    ports:
      - "127.0.0.1:4001:8080"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=TripKioskDev
      - DEPLOYMENT_HOST=https://travel-info.cz/api
    depends_on:
      - "mongodb"
  mongodb:
    image: mongo
    volumes:
      - ./persist/mongodb:/data/db
  vue:
    image: janvesely92/dt-frontend
    ports:
      - "127.0.0.1:4000:80"
    depends_on:
      - "ktor"